export const PROFILE = {
  name: "Sujan Mandal",
  role: "UI/UX Designer",
  location: "Kolkata, India",
  email: "sujanmandal2393@gmail.com",
  linkedin: "https://www.linkedin.com/in/hey-sujan/",
  behance: "https://www.behance.net/sujanmandal20",
  summary: "Product-focused UI/UX design student building accessible, user-centered digital experiences. Skilled in design systems, high-fidelity interfaces, prototyping, responsive design, and seamless developer handoff.",
  profileImage: "/assets/images/profile-image.jpeg",
};

export const EXPERIENCE = [
  {
    role: "UX Designer Intern",
    company: "Nashbud",
    period: "April 2026 – Present",
    description: "Designing responsive web and mobile interfaces while building scalable design systems. Focusing on high-fidelity prototyping and seamless developer handoff.",
    responsibilities: [
      "Designed responsive web and mobile interfaces",
      "Built scalable design systems using Auto Layout, Components and Variants",
      "Created interactive prototypes for user testing and stakeholder review",
      "Collaborated closely with developers to ensure design fidelity",
      "Improved user flows to reduce friction and enhance accessibility",
      "Created custom illustrations and visual assets",
      "Ensured design consistency across all digital touchpoints",
    ],
  },
];

export const EDUCATION = [
  {
    degree: "Bachelor of Technology",
    major: "Electronics and Communication Engineering (ECE)",
    institution: "Narula Institute of Technology",
  },
];

export const SKILLS = {
  design: [
    "UI Design",
    "UX Research",
    "Wireframing",
    "Prototing",
    "Design Systems",
    "Responsive Design",
    "Accessibility",
    "Information Architecture",
    "User Flows",
    "Visual Hierarchy",
  ],
  tools: [
    "Figma",
    "FigJam",
    "Illustrator",
    "Notion",
    "AI Design Tools",
  ],
  technical: [
    "HTML",
    "React",
    "Flutter Architecture Awareness",
  ],
};

export const PROJECTS = [
  {
    id: "headless-commerce",
    title: "Headless Commerce Website – UX Case Study",
    category: "Web UX Design",
    description: "A comprehensive UX case study redesigning a headless commerce experience for seamless, high-conversion product discovery.",
    longDescription: "This case study explored how headless architecture enables richer, more flexible shopping experiences. The focus was on optimizing the user journey from discovery to checkout.",
    problem: "Traditional monolithic commerce platforms restrict UX innovation. The challenge was designing a content-first, performance-driven shopping flow.",
    goal: "Design an intuitive headless commerce experience that reduces friction, elevates product storytelling, and boosts conversion.",
    solution: "A modular, component-driven UX system with dynamic content zones, streamlined navigation, and a frictionless checkout.",
    research: "Competitive analysis of leading headless commerce sites and heuristic evaluation of existing product flows.",
    process: "From journey mapping and wireframes to high-fidelity prototypes tested with real users across device types.",
    tech: ["Figma", "UX Research", "Information Architecture"],
    impact: "Simplified the purchase funnel and improved content discoverability through modular page architecture.",
    image: "/assets/images/proj_headless_commerce.jpg",
    behanceUrl: "https://www.behance.net/gallery/246681539/Headless-Commerce-Website-UX-Case-Study",
  },
  {
    id: "neith-mobile-homepage",
    title: "NEITH — Luxury Fashion Mobile & Homepage Redesign ✨",
    category: "Mobile UX Design",
    description: "A premium redesign of the NEITH luxury fashion brand across mobile and web — blending editorial aesthetics with conversion-focused UX.",
    longDescription: "NEITH required a digital presence as refined as its physical collections. This dual-channel redesign elevated the brand experience across mobile and homepage touchpoints.",
    problem: "The existing NEITH digital interface lacked the editorial tension and tactile luxury that customers experienced in-store.",
    goal: "Translate the brand's haute couture identity into a digital experience that feels exclusive, immersive, and conversion-ready.",
    solution: "A full-bleed editorial design language with cinematic hero sections, curated typography, and a mobile-first interaction model.",
    research: "Brand auditing, luxury benchmark analysis, and user interviews with high-income fashion consumers.",
    process: "Concept moodboarding, visual direction definition, wireframing, and iterative high-fidelity design.",
    tech: ["Figma", "UI Design", "Luxury Branding"],
    impact: "Elevated brand perception and improved mobile engagement through a distinctly premium visual language.",
    image: "/assets/images/proj_neith_mobile.jpg",
    behanceUrl: "https://www.behance.net/gallery/249276273/NEITH-Luxury-Fashion-Mobile-Homepage-Redesign-",
  },
  {
    id: "neith-homepage",
    title: "NEITH — Luxury Fashion Homepage Redesign",
    category: "Luxury Ecommerce UX",
    description: "A focused homepage redesign for NEITH, creating a luxury e-commerce first impression that balances aesthetics and conversion.",
    longDescription: "The homepage is the most critical conversion surface. For NEITH, it needed to instantly communicate brand prestige while guiding users toward discovery and purchase.",
    problem: "The homepage failed to establish brand authority or create a compelling reason to explore further, leading to high bounce rates.",
    goal: "Design a homepage that commands attention, communicates exclusivity, and drives meaningful user engagement.",
    solution: "Cinematic hero imagery, asymmetric editorial layouts, and strategic CTA placement inspired by luxury print campaigns.",
    research: "Analysis of conversion patterns on luxury e-commerce sites and scroll behavior heatmap review.",
    process: "Rapid ideation, mood boarding, multiple concept directions, stakeholder review, and high-fidelity execution.",
    tech: ["Figma", "Ecommerce UX", "Visual Design"],
    impact: "Increased time-on-page and reduced bounce rate through a more compelling homepage narrative.",
    image: "/assets/images/proj_neith_homepage.jpg",
    behanceUrl: "https://www.behance.net/gallery/249274977/NEITH-Luxury-Fashion-Homepage-Redesign",
  },
  {
    id: "clinical-dashboard",
    title: "Clinical Dashboard for Menstrual Cycle Intelligence",
    category: "Healthcare Dashboard",
    description: "A data-rich clinical dashboard designed for healthcare professionals to monitor and interpret menstrual health intelligence.",
    longDescription: "This healthcare product required careful balance between medical data density and clinical usability. The design needed to support both clinicians and patients in understanding complex cycle data.",
    problem: "Clinicians lacked a unified, interpretable interface for menstrual health data — critical information was fragmented across incompatible systems.",
    goal: "Create a clinical-grade dashboard that surfaces actionable cycle intelligence in a clear, accessible interface for medical professionals.",
    solution: "A modular dashboard with cycle phase visualizations, anomaly flagging, patient history timelines, and predictive health indicators.",
    research: "User interviews with gynecologists and OB-GYNs, clinical workflow analysis, and accessibility research for medical interfaces.",
    process: "Information architecture mapping, data visualization exploration, clinical UX heuristics review, and iterative prototyping.",
    tech: ["Figma", "Data Visualization", "Healthcare UX"],
    impact: "Improved clinical decision-making efficiency by consolidating dispersed health signals into a single coherent view.",
    image: "/assets/images/proj_clinical_dashboard.jpg",
    behanceUrl: "https://www.behance.net/gallery/248718383/Clinical-Dashboard-for-Menstrual-Cycle-Intelligence",
  },
  {
    id: "variant-management",
    title: "Variant Management for Small Business Owners",
    category: "Mobile Product Design",
    description: "A mobile-first product variant management tool designed to reduce complexity for small business owners managing inventory.",
    longDescription: "Small business owners often struggle with the complexity of product variant management across e-commerce platforms. This solution simplifies the process significantly.",
    problem: "Existing inventory tools are either too simple or too complex for small business owners, leading to errors and time waste.",
    goal: "Design a mobile product management flow that makes variant creation, editing, and inventory tracking intuitive for non-technical users.",
    solution: "A guided, step-by-step variant builder with visual selectors, bulk editing capabilities, and clear SKU management.",
    research: "Contextual inquiry with small business owners, task analysis of existing commerce platform workflows.",
    process: "User journey mapping, low-fi wireframes, usability testing with small business owners, high-fidelity iteration.",
    tech: ["Figma", "Mobile Design", "UX Research"],
    impact: "Reduced time-to-list new product variants and lowered error rates in inventory management.",
    image: "/assets/images/proj_variant_mgmt.jpg",
    behanceUrl: "https://www.behance.net/gallery/247758695/Variant-Management-for-Small-Business-Owners",
  },
  {
    id: "kiddos-edtech",
    title: "Kiddos — Ed-Tech App",
    category: "EdTech",
    description: "A gamified, child-friendly educational app designed to make learning engaging, measurable, and fun for young learners.",
    longDescription: "Kiddos was built to bridge the gap between screen entertainment and educational value, using game mechanics to sustain attention and foster genuine learning.",
    problem: "Children disengage from generic educational apps quickly. Parents lack visibility into actual learning progress.",
    goal: "Design an ed-tech app that children want to use and that gives parents meaningful insight into their child's learning journey.",
    solution: "A gamified learning environment with achievement systems, visual progress maps, interactive lessons, and parent dashboards.",
    research: "Child usability testing, child development psychology research, and parent interviews on educational app usage.",
    process: "Play-based UX principles, character concept development, wireframing, accessibility testing with young users.",
    tech: ["Figma", "EdTech UX", "Gamification"],
    impact: "Sustained in-app engagement through reward mechanics and reduced parental anxiety through transparent progress reporting.",
    image: "/assets/images/proj_kiddos.jpg",
    behanceUrl: "https://www.behance.net/gallery/247641161/Kiddos-a-Ed-Tech-app",
  },
  {
    id: "seren-editorial",
    title: "SEREN — Editorial Interface Design",
    category: "Editorial Experience",
    description: "An editorial interface design for SEREN — a premium digital publication that elevates the reading and discovery experience.",
    longDescription: "SEREN required a digital editorial experience that respected and elevated long-form content, blending print tradition with modern digital interactivity.",
    problem: "Most digital publication interfaces prioritize quantity over quality, undermining the editorial integrity of premium content.",
    goal: "Design an editorial interface that creates the feeling of a curated, high-quality publication in a digital-first format.",
    solution: "A typographic-led design system with editorial grids, immersive full-bleed imagery, and intentional white space.",
    research: "Analysis of award-winning editorial websites, typographic studies, and reading pattern research.",
    process: "Visual language exploration, typography pairing, grid system design, and interactive prototype development.",
    tech: ["Figma", "Editorial Design", "Typography"],
    impact: "Elevated perceived content quality and increased reading session duration through immersive editorial design.",
    image: "/assets/images/proj_seren.jpg",
    behanceUrl: "https://www.behance.net/gallery/247326107/SEREN-Editorial-Interface-Design",
  },
  {
    id: "book-recommendation-app",
    title: "Mobile Book Recommendation App – UI/UX Design",
    category: "Mobile App",
    description: "A personalized mobile book discovery app that curates reading recommendations through intelligent preference mapping.",
    longDescription: "Designed for avid readers who feel overwhelmed by choice, this app creates a warm, curated reading companion that understands your taste.",
    problem: "Book discovery is frustrating — readers struggle to find their next read among thousands of overwhelming options.",
    goal: "Design a mobile app that makes book discovery feel personal, serendipitous, and enjoyable.",
    solution: "A taste-profiling onboarding flow, mood-based recommendation engine UI, social reading features, and a minimal reading tracker.",
    research: "Reader interviews, competitive analysis of Goodreads and StoryGraph, and content discovery pattern research.",
    process: "User flow mapping, information architecture, wireframing, high-fidelity design, and micro-interaction design.",
    tech: ["Figma", "Mobile UX", "UI Design"],
    impact: "Improved discovery delight and increased reading list conversion through mood-driven recommendation UX.",
    image: "/assets/images/proj_book_app.jpg",
    behanceUrl: "https://www.behance.net/gallery/246229129/Mobile-Book-Recommendation-App-UIUX-Design",
  },
  {
    id: "sent-prototype",
    title: "sen-t — Event Management Platform Prototype (Figma)",
    category: "Event Platform",
    description: "A high-fidelity Figma prototype of sen-t, an end-to-end event management platform built for modern organizers.",
    longDescription: "sen-t was designed to simplify the complexity of event management — from ticketing and promotion to attendee experience and post-event analytics.",
    problem: "Event organizers use too many disconnected tools. There is no unified platform that handles the full event lifecycle elegantly.",
    goal: "Prototype a cohesive event management platform that streamlines every phase of event creation, promotion, and execution.",
    solution: "A modular platform with event creation wizards, smart ticketing flows, attendee management, and integrated analytics.",
    research: "Interviews with event organizers, competitive teardowns of Eventbrite and Luma, and workflow analysis.",
    process: "Platform architecture mapping, component-based Figma system, interactive prototype for user testing.",
    tech: ["Figma", "Prototyping", "UX Design"],
    impact: "Validated a unified event management workflow that reduced tool-switching and organizer cognitive load.",
    image: "/assets/images/proj_sent_prototype.jpg",
    behanceUrl: "https://www.behance.net/gallery/246200571/sen-t-Event-Management-Platform-Prototype-%28Figma%29",
  },
  {
    id: "sent-website",
    title: "sen-t — Event Management Website UI/UX Case Study",
    category: "Website UX",
    description: "A full UX case study of the sen-t marketing website — designed to convert event organizers and drive platform adoption.",
    longDescription: "The sen-t website needed to communicate the platform's value proposition to a sophisticated B2B audience of event professionals.",
    problem: "The original website lacked clear messaging, a compelling visual hierarchy, and a conversion-optimized user journey.",
    goal: "Design a website that clearly communicates sen-t's value, builds trust, and drives sign-up conversions among event organizers.",
    solution: "A conversion-optimized marketing site with clear value proposition hierarchy, social proof integration, and guided CTAs.",
    research: "Stakeholder interviews, landing page conversion best practices, and competitor website benchmarking.",
    process: "Content strategy, sitemap design, wireframing, visual design, and A/B test scenario planning.",
    tech: ["Figma", "Web UX", "Conversion Design"],
    impact: "Improved landing page clarity and created a scalable website system for ongoing marketing campaigns.",
    image: "/assets/images/proj_sent_website.jpg",
    behanceUrl: "https://www.behance.net/gallery/246200019/sen-t-Event-Management-Website-UIUX-Case-Study",
  },
  {
    id: "eventpluse",
    title: "EventPluse — Event Management",
    category: "SaaS Platform",
    description: "A full-featured SaaS event management platform designed to handle large-scale events with enterprise-grade analytics.",
    longDescription: "EventPluse targets professional event management companies and corporate event teams who need robust, scalable tooling.",
    problem: "Enterprise event teams lack a modern, scalable platform that unifies event operations, attendee management, and business intelligence.",
    goal: "Design a comprehensive SaaS platform that gives enterprise event teams complete control over every aspect of event delivery.",
    solution: "A role-based SaaS platform with a powerful organizer dashboard, real-time analytics, multi-event management, and CRM integration.",
    research: "Enterprise sales workflow analysis, event industry stakeholder interviews, and SaaS UX best practice research.",
    process: "Product discovery, feature prioritization, design system creation, dashboard UX design, and usability testing with event professionals.",
    tech: ["Figma", "SaaS Design", "Data Visualization"],
    impact: "Delivered a scalable platform design that addressed the full complexity of enterprise event management workflows.",
    image: "/assets/images/proj_eventpluse.jpg",
    behanceUrl: "https://www.behance.net/gallery/246134059/EventPluse-Event-Management",
  },
];
